# Generated by Django 5.2.4 on 2025-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='bbfc_rating',
            field=models.CharField(blank=True, choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('15', '15'), ('18', '18')], max_length=2, null=True),
        ),
    ]
