# Generated by Django 5.2.4 on 2025-07-24 23:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_media_cover_remove_media_year_media_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='media',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='media',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
