# Generated by Django 5.2.4 on 2025-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_media_bbfc_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='media',
            name='year',
        ),
        migrations.AddField(
            model_name='media',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
