# Generated by Django 5.2.4 on 2025-07-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_publisher_alter_media_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
