# Generated by Django 5.2.4 on 2025-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_media_publisher_delete_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='publisher',
        ),
    ]
